### ISSUE TITLE
Sample app not working

### ISSUE THREAD

**Issue by oanaBan** [oovoodev/iOS-SDK-Sample#10]
I downloaded your sample app (v 1.4) from github and it's not working, I'm getting 
/Users/...ooVooSample/AppDelegate.m:10:9: 'ooVooController.h' file not found.
I also added manually the ooVoo.framework under my Frameworks folder but it still doesn't work.

Any ideea ?

**Comment by eakraly** [comment]
Hi @oanaBan,
Still having the issue?
