### ISSUE TITLE
Create participant and invite participant to join call.

### ISSUE THREAD

**Issue by kjha1991** [oovoodev/iOS-SDK-Sample#15]
I want to develop app where one can create conference and must be able to invite user to conference. Now I want to know how following is possible : 
 - How can I create Participant ID for any of my user and save it for future use? Is it like Conference ID where anything can be conference id and should managed by application not by SDK?
 - Is there any way to invite person to join a conference additionally if possible user will be prompted even if application is not running in background like phone call?

**Comment by eranmalovany** [comment]
Hi,
it's your App logic to decide how to generate a user ID, same as conference ID.
we are going to release a new version next month support chat and signaling, which will give you the ability to initiate a call. This version will not support push messaging yet, but push messaging will follow later this year.
