### ISSUE TITLE
ooVoo SDK initialization failed with result

### ISSUE THREAD

**Issue by kermankohli** [oovoodev/iOS-SDK-Sample#2]
I'm getting the following error:

ooVoo SDK initialization failed with result 3

The details are:

#define APP_ID_SETTINGS_KEY       @"APPID"
#define APP_TOKEN_SETTINGS_KEY    @"AxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAREALLYLONGAPPTOKEN"
#define BACKEND_URL_SETTINGS_KEY  @"https://api-sdk.dev.oovoo.com/"

**Comment by eakraly** [comment]
Is this issue still relevant @veibhav ?

**Comment by bhavikmpatel** [comment]
what is your pricing list for your sdks.
