### ISSUE TITLE
Warnings inside pod ooVooSDK2 (2.0.0.97)

### ISSUE THREAD

**Issue by alexwillingham** [oovoodev/iOS-SDK-Sample#20]
ld: warning: instance method 'isSslVerifyPeer' in category from xxxxx/Pods/ooVooSDK2/ooVooSDK.framework/ooVooSDK(ooVooClientWrap.o) overrides method from class in xxxxx/Pods/ooVooSDK2/ooVooSDK.framework/ooVooSDK(ooVooClientWrap.o)

**Comment by eakraly** [comment]
Thanks @alexwillingham, we are looking into it. Will be fixed in 2.1.
