### ISSUE TITLE
Rebuild oovooSDK.framework with bitcode enabled

### ISSUE THREAD

**Issue by alexwillingham** [oovoodev/iOS-SDK-Sample#21]
../Pods/ooVooSDK2/ooVooSDK.framework/ooVooSDK(AVChatWrap.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7

**Comment by eakraly** [comment]
Hi @alexwillingham,
Thanks for your report. We are about to release a new version of our SDK but it will not contain bitcode - it requires support from 3rd party libraries that we use and do not provide bitcode yet.
