### ISSUE TITLE
Crash EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0xa006d6f74746f43e (3)

### ISSUE THREAD

**Issue by sadgb** [oovoodev/iOS-SDK-Sample#22]
Hey guys, got this crash on client's  ios 9.1 device. Latest version ooVooSDK, no Jailbreak

Thread : Crashed: com.apple.main-thread
0  Remsmed                        4297479484 boost::asio::detail::kqueue_reactor::deregister_descriptor(int, boost::asio::detail::kqueue_reactor::descriptor_state*&, bool) + 716
1  Remsmed                        4297597540 boost::asio::basic_io_object<boost::asio::stream_socket_service<boost::asio::ip::tcp>, true>::~basic_io_object() + 1256
2  Remsmed                        4297479484 boost::asio::detail::kqueue_reactor::deregister_descriptor(int, boost::asio::detail::kqueue_reactor::descriptor_state*&, bool) + 716
3  Remsmed                        4299763432 boost::scoped_ptr<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > >::~scoped_ptr() + 731000
4  Remsmed                        4298381920 curl::multi::socket_cleanup(int) + 764872
5  Remsmed                        4299756584 curl::easy::closesocket(void*, int) + 724152
6  Remsmed                        4298282540 conn_free (url.c:2681)
7  Remsmed                        4298282328 Curl_disconnect (url.c:2793)
8  Remsmed                        4298202740 curl_multi_cleanup (sigpipe.h:66)
9  Remsmed                        4298381116 curl::multi::~multi() + 764068
10 Remsmed                        4297479484 boost::asio::detail::kqueue_reactor::deregister_descriptor(int, boost::asio::detail::kqueue_reactor::descriptor_state*&, bool) + 716
11 Remsmed                        4300296292 oovoo::http_manager::~http_manager() + 86404
12 libc++.1.dylib                 6842136072 std::__1::__shared_weak_count::__release_shared() + 60
13 Remsmed                        4297318080 oovoo::sdk::connection::HttpsConnection::~HttpsConnection() + 128332
14 Remsmed                        4297318112 oovoo::sdk::connection::HttpsConnection::~HttpsConnection() + 128364
15 Remsmed                        4297319500 std::__1::unique_ptr<oovoo::sdk::connection::HttpsConnection, std::__1::default_delete<oovoo::sdk::connection::HttpsConnection> >::~unique_ptr() + 129752
16 libsystem_c.dylib              6861551556 __cxa_finalize_ranges + 428
17 libsystem_c.dylib              6861201252 exit + 24
18 UIKit                          6594755544 +[_UIAlertManager hideAlertsForTermination] + 526
19 UIKit                          6596973560 __102-[UIApplication _handleApplicationDeactivationWithScene:shouldForceExit:transitionContext:completion:]_block_invoke1974 + 316
20 UIKit                          6596986220 _runAfterCACommitDeferredBlocks + 292
21 UIKit                          6597039292 _cleanUpAfterCAFlushAndRunDeferredBlocks + 92
22 UIKit                          6594107780 _afterCACommitHandler + 96
23 CoreFoundation                 6504135632 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
24 CoreFoundation                 6504126836 __CFRunLoopDoObservers + 372
25 CoreFoundation                 6504127908 __CFRunLoopRun + 928
26 CoreFoundation                 6503271584 CFRunLoopRunSpecific + 384
27 GraphicsServices               6690160776 GSEventRunModal + 180
28 UIKit                          6594596860 UIApplicationMain + 204
29 Remsmed                        4296834436 main (AppDelegate.swift:20)
30 libdyld.dylib                  6860957880 start + 4

Can't figure out valid STR.

**Comment by eakraly** [comment]
Hi @sadgb,
This is a known issue - we will fix it in next release.
Thanks for reporting!
