### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by codeflair** [oovoodev/iOS-SDK-Sample#23]
using old sdk version  iOS.54--2014-06-24_19-41-44
Assertion failed: (!pMsg), function OnReceiveInternal, file /var/jenkins/workspace/oovoosdk-iOS-Bundle-1.2/src/ClientCore/AvsClient.cpp, line 621.

**Comment by eakraly** [comment]
Thank you @codeflair,

These version is obsolete and not supported.
Please upgrade to latest released SDK.
