### ISSUE TITLE
Open Back Camera

### ISSUE THREAD

**Issue by rauljuarez** [oovoodev/iOS-SDK-Sample#24]
Hi, im trying to set the use of the Back Camera. And it's impossible  

My Code So far:
 ```
...
self.view.addSubview(self.videoPanel)
                    self.sdk.AVChat.VideoController.bindVideoRender("raul.alberto.juarez", render: self.videoPanel)
                    self.sdk.AVChat.VideoController.setConfig(String(arr_devices[0]), forKey: ooVooVideoControllerConfigKey.CaptureDeviceId)
                    self.sdk.AVChat.VideoController.openCamera() // -> will return  didCameraStateChange Delegate
```
According to the Documentationn, this is the way to go, but black panel shows up. If i dont set any camera,  and use the one by default, all works fine. Any ideas?

**Comment by eakraly** [comment]
Hi @rauljuarez ,
Could you please provide log of SDK from your application?
Also -  what does arr_devices[] contain? Is it empty? Does it have more than 1 entry?

**Comment by jaboutboul** [comment]
@rauljuarez Any updates? Are you able to provide us with those logs?

**Comment by rauljuarez** [comment]
Sorry guys i was able to it, was a minimal detail in my code. We can close this.

**Comment by jaboutboul** [comment]
Thanks!
