### ISSUE TITLE
Sample doesn't build and has concerning warnings with oovoo SDK 2.2.0.72, Xcode 7.2

### ISSUE THREAD

**Issue by alexwillingham** [oovoodev/iOS-SDK-Sample#25]
Seems that the SDK listed in cocoapods as 2.2.0.72 was built with minimum SDK specified as 9.1 leading to a bunch of warnings as the sample project seeks to support iOS 7.1 ('iOS Deployment Target').  I've already begun correspondence about these via oovoo support tickets.  

The sample doesn't build under Xcode 7.2 (7C68) because the library appears to include two copies of all object files. I've included a full listing of the duplicates, and the warnings mentioned, but in brief, they appear as:

duplicate symbol _OBJC_METACLASS_$_ooVooDeviceWrap in:
    /Users/alexwillingham/clientWork/pacify/iOS-SDK-Sample/Pods/ooVooSDK2/ooVooSDK.framework/ooVooSDK(DeviceWrap.o)
    /Users/alexwillingham/clientWork/pacify/iOS-SDK-Sample/Pods/ooVooSDK2/ooVooSdk.framework/ooVooSdk(DeviceWrap.o)
duplicate symbol _OBJC_IVAR_$_ooVooDeviceWrap._middleImpl in:
    /Users/alexwillingham/clientWork/pacify/iOS-SDK-Sample/Pods/ooVooSDK2/ooVooSDK.framework/ooVooSDK(DeviceWrap.o)
    /Users/alexwillingham/clientWork/pacify/iOS-SDK-Sample/Pods/ooVooSDK2/ooVooSdk.framework/ooVooSdk(DeviceWrap.o)
duplicate symbol _OBJC_CLASS_$_RSCIW_ID in:

Review the attached gist for the complete mess.

https://gist.github.com/alexwillingham/8b3fd77f6c8e69a677d8

As a note, it would be appreciated if you would commit Podfile.lock with your sample so that we can see what version of the oovoo2 SDK and version of cocoapods were used for the most recent successful compilation.

**Comment by eakraly** [comment]
Hi @alexwillingham ,
Please make sure you do not link 2 copies of SDK

**Comment by alexwillingham** [comment]
@eakraly Thanks for your note.  These errors are from a fresh clone of this repo's master branch, running pod install (cocoapods v 0.39.0, the latest) one time.  Indeed, there are multiple copies of the SDK linked, why does the sample project do this?

![image](https://cloud.githubusercontent.com/assets/3759688/11812833/33857fa4-a30c-11e5-8e3e-876ba6f14a88.png)

You must remove 'ooVooSdk.framework' to run.  Would be good to either remove this from the project so cocoapods works as expected, or update documentation to include the need to remove this manually.

![image](https://cloud.githubusercontent.com/assets/3759688/11812864/60d8c704-a30c-11e5-9708-a289ff034191.png)

**Comment by eakraly** [comment]
@alexwillingham Bug in the workspace of sample :)

**Comment by jaboutboul** [comment]
Thanks @alexwillingham for the feedback. This should be fixed in commit aab54cb.
