### ISSUE TITLE
ooVoo failed

### ISSUE THREAD

**Issue by bravemount** [oovoodev/iOS-SDK-Sample#7]
ooVoo SDK initialization failed with result 1

On Launch: @"ooVoo SDK - init- Error"
when tapped join : @"App ID not valid"

My user id : dayakar.s@bravemount.com

AppID:12349983351916
Token: MDAxMDAxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqLw9zhnYysSHH%2B9JR%2Bt8FPotqmf%2F5EHW5xaa%2FK4R8hv3mP61CmC1QNEmpY4G74X3vS5b19%2Bb%2FcRBk7R1PCDWWgAYQZyAAH5xzgcKhmLohhfRvASZ7HnvKlAaJOjIcwR8%3D

**Comment by eakraly** [comment]
Hi,
Is this still relevant?
