### ISSUE TITLE
No 64bit arctechture support yet ?

### ISSUE THREAD

**Issue by lorencogonzaga** [oovoodev/iOS-SDK-Sample#9]
Hi there!
Downloaded the oovoo iOS SDK and it runs OK in the simulator until Iphone 5 devices.
Once I switch to iPhone 5S above or try in 5S device it crash displaying the following error

No architectures to compile for (ONLY_ACTIVE_ARCH=YES, active arch=x86_64, VALID_ARCHS=i386).

**Comment by andrewlchen** [comment]
Hi! 

I wanted to follow up on this thread as well. Has 64-bit support for Oovoo's iOS SDK already shipped? Is it now in the current version of the SDK available on the Oovoo website?

**Comment by oanaBan** [comment]
@andrewlchen Oovoo's iOS SDK has 64-bit support on release 1.4

**Comment by lorencogonzaga** [comment]
Whats the easiest way to upgrade to the new 64-bit SDK from a previous project using the oldest SDK version ?

Cheers

**Comment by eakraly** [comment]
Is this issues still relevant to anyone?
